[general]
project_name = 'EVE-Images'
workers = 8
utils_backup_folder = 'D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\backups'
only_once_per_task = ["UI: Bookmarks", "UI: Notifications", "UI: Selected object", "UI: Warehouse",
"UI: Navigation", "UI: Overview panel", "UI: Ship fitting", "UI: Station infopanel"]

[templates]
'UI: Bookmarks' = ['D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\bookmarks.png']
'UI: Notifications' = ['D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\notifications.png']
'UI: Selected object' = ['D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\selected_object.png',
                        'D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\selected_object_2.png',
                        'D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\selected_object_3.png',]
'UI: Warehouse' = ['D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\warehouses.png',
                    'D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\warehouses_2.png',
                    'D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\warehouses_3.png']
'UI: Navigation' = ['D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\navigation.png',
                    'D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\navigation_2.png',
                    'D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\navigation_3.png',
                    'D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\navigation_4.png',
                    'D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\navigation_5.png',
                    'D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\navigation_6.png']
'UI: Overview panel' = ['D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\overview panel.png',
                        'D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\overview panel_2.png',
                        'D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\overview panel_3.png',
                        'D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\overview panel_4.png',
                        'D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\overview panel_5.png']
'UI: Ship fitting' = ['D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\ship_fitting.png']
'UI: Station infopanel' = ['D:\Projects\Eve-Online-Mining-Bot\cv_eve\utils\templates\station_infopanel.png']
